general.live_config_reload = true

general.import = [
  "~/prd/src/ohohama/alacritty/themes/ohohama.toml",
]

[window]
dimensions = {columns = 200, lines = 60}
opacity = 100
padding = {x = 8, y = 4}

[cursor]
style = "Beam"

[scrolling]
history = 100000
multiplier = 3

[font]
builtin_box_drawing = true
glyph_offset = {x = 0, y = -1}
normal = {family = "Hack Nerd Font", style = "Regular"}
offset = {x = 0, y = 0}
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"
