# A-B loop を 0–4 秒に初期化
r set ab-loop-a no ; set ab-loop-b no ; set ab-loop-a 0 ; set ab-loop-b 4 ; set time-pos 0

# 4秒ずつ後ろへ
c add ab-loop-a 4 ; add ab-loop-b 4 ; add time-pos 4

# 4秒ずつ前へ
C add ab-loop-a -4 ; add ab-loop-b -4 ; add time-pos -4

# A点へ戻る
x seek ${ab-loop-a} absolute

# Play/Pause
SPACE cycle pause